FROM node:22-alpine

WORKDIR /app

# Copie des fichiers de dépendances et installation
COPY package*.json ./
RUN npm install

# Copie du code source
COPY . .

# Configuration de l'hôte et du port pour Docker
ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321

# Lancement du serveur Astro
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--force"]