services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tavern
      POSTGRES_PASSWORD: root
