name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for backend
      run: docker build ./backend --tag tavern-backend:${{ github.sha }}
    - name: Build the Docker image for frontend
      run: docker build ./frontend --tag tavern-frontend:${{ github.sha }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker backend image
      run: |
        docker push 20220796/tavern-backend:${{ vars.APP_VERSION }}
        docker push 20220796/tavern-backend:${{ github.sha }}

    - name: Push Docker frontend image
      run: |
        docker push 20220796/tavern-frontend:${{ vars.APP_VERSION }}
        docker push 20220796/tavern-frontend:${{ github.sha }}

